defaults: &defaults
  provider: 'AWS'
  aws_access_key_id: <%= ENV['AWS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_ACCESS_KEY'] %>
  region: 'sa-east-1'
development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults